### ISSUE TITLE
Produire une coupe suivant une ligne brisée

### ISSUE THREAD

**Issue by mraynauld** [nicolasBenoit1/matlab-tools#2]
@nicolasBenoit1  Est-ce qu'il serait possible d'adapter la fonction geologicCrossSection pour que l'on puisse faire une coupe le long d'une ligne brisée comme par exemple la coupe ABC présentée dans l'image ci-dessous:
![image](https://user-images.githubusercontent.com/43883332/59627570-87790080-910c-11e9-852b-21fd90d3bec8.png)
Merci!

**Comment by nicolasBenoit1** [comment]
Done
